### PR TITLE
Music Added

### PR DESCRIPTION
**Pull request by HawkItzme**
Please merge @utkarsh006

### CODE REVIEW

**Comment by utkarsh006** [comment]
@HawkItzme Add video showing changes to your app.

**Comment by HawkItzme** [comment]
@utkarsh006 already added, see the Issue page please

**Comment by HawkItzme** [comment]
@utkarsh006 already added, see the Issue page please

**Comment by utkarsh006** [comment]
It looks great ! Thanks for your contribution :)

**Pull request merged**
