### PR TITLE
Display dialog box message when the Game is Tied.

### PR DESCRIPTION
**Pull request by HawkItzme**
Hey @utkarsh006 please review and merge my PR.

### CODE REVIEW

**Comment by utkarsh006** [comment]
@HawkItzme Follow the guidelines. Star the repo and attach the video of how your changes are looking.

**Comment by HawkItzme** [comment]
Okay

**Comment by HawkItzme** [comment]
My Changes 

https://user-images.githubusercontent.com/86477458/184034095-579dd960-6fa2-4ea0-95f2-10c958121424.mp4

@utkarsh006

**Comment by utkarsh006** [comment]
@HawkItzme In the original version, the status bar is not there. Kindly remove that and show me the results in the video from the scratch i.e. when player 1 and 2 wins and also the condition when game ties.

**Comment by HawkItzme** [comment]
Sure, wait. 
But I didn't touched the other files. Is it possible that status bar can come on it's own? Just clarifying @utkarsh006

**Comment by utkarsh006** [comment]
@HawkItzme YES, probably you slightly have changed the code. Look into the issue carefully and then make a commit.

**Comment by HawkItzme** [comment]
Yeah i got it, it was happening because I was using Dark mode and in the night theme Action Bar was not removed.  Just committing the changes along with the demo video, it's working fine now.

**Comment by HawkItzme** [comment]
My Demo Video  @utkarsh006 

https://user-images.githubusercontent.com/86477458/184122806-f499bb0c-239a-4372-9da0-c685d0701158.mp4

**Comment by utkarsh006** [comment]
Thanks for your Contribution 🎈

**Pull request merged**
